# Generated by Django 4.2.5 on 2023-10-17 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_itemlist_itemisactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='itemWatchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='itemInWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
