# Generated by Django 4.2.5 on 2023-10-18 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_itemlist_itemwatchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('authorComment', models.ManyToManyField(blank=True, null=True, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
