# Generated by Django 4.2.5 on 2023-10-18 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_itemcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcomments',
            name='itemDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='auctions.itemlist'),
        ),
        migrations.RemoveField(
            model_name='itemcomments',
            name='authorComment',
        ),
        migrations.AddField(
            model_name='itemcomments',
            name='authorComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userComment', to=settings.AUTH_USER_MODEL),
        ),
    ]
