# Generated by Django 4.2.5 on 2023-10-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_itemcomments_itemdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcomments',
            old_name='comment',
            new_name='dbComment',
        ),
    ]
